default_agent: elgato_mcp
agents:
  elgato_mcp:
    name: elgato_mcp
    entrypoint: elgato_mcp.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::135112444960:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-86db2f38a2
      execution_role_auto_create: false
      account: '135112444960'
      region: us-west-2
      ecr_repository: 135112444960.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-elgato_mcp
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: elgato_mcp-4R07IYFXqM
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:135112444960:runtime/elgato_mcp-4R07IYFXqM
      agent_session_id: d59b6781-038e-46da-8de6-94b8505abf46
    codebuild:
      project_name: bedrock-agentcore-elgato_mcp-builder
      execution_role: arn:aws:iam::135112444960:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-86db2f38a2
      source_bucket: bedrock-agentcore-codebuild-sources-135112444960-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
